- name: "Create stack directory"
  ansible.builtin.file:
    path: "~/templates/{{ item.STACK_NAME }}"
    state: directory
    mode: "0755"
  with_items: "{{ gas_docker_DCCT_settings }}"

- name: "Create docker-compose.yml"
  template:
    src: files/docker-compose.yml.j2
    dest: "{{ gas_docker_DCCT_base_template_dir }}/{{ item.STACK_NAME }}/docker-compose.yml"
    mode: 0644
  with_items: "{{ gas_docker_DCCT_settings }}"
  
# - name: Deploy stack from a compose file
#  community.docker.docker_stack:
#    state: present
#    name: "{{ item.STACK_NAME }}"
#    compose:
#      - "{{ gas_docker_DCCT_base_template_dir }}/{{ item.STACK_NAME }}/docker-compose.yml"
#  with_items: "{{ gas_docker_DCCT_settings }}"
